### ISSUE TITLE
Feature 1: User can search for a cocktail

### ISSUE THREAD

**Issue by john-hc-hwang** [john-hc-hwang/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a cocktail

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can search for a cocktail

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Home Screen](https://user-images.githubusercontent.com/79896352/121104445-f139bb80-c7b6-11eb-906e-99fa8e4b2e19.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can search for a specific cocktail
- [x] Returns lists (pictures & descriptions) of cocktails matching in name
- [x] If no cocktail was found, return "No such cocktail found :("
- [x] **Make sure when user clicks on top Cocktailz label, they get redirected to main page with search and add features.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
