### ISSUE TITLE
Feature 3: User can edit, remove, rate the cocktail

### ISSUE THREAD

**Issue by john-hc-hwang** [john-hc-hwang/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit, remove, rate the cocktail

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can edit, remove, rate the cocktail

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![My Cocktailz](https://user-images.githubusercontent.com/79896352/121104812-ae2c1800-c7b7-11eb-8057-cba4699119a3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can edit their cocktail in "My cocktailz"
- [x] User can remove their cocktail in "My cocktailz"
- [x] user can rate their cocktail in "My cocktailz"
- [x] Users should be able to refresh the page and still have their cocktails in "My cocktailz" (local storage)

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
