### ISSUE TITLE
Feature 4: User can add their own cocktail to "My cocktailz"

### ISSUE THREAD

**Issue by john-hc-hwang** [john-hc-hwang/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add their own cocktail to "My cocktailz"

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add their own cocktail to "My cocktailz"

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Make your own](https://user-images.githubusercontent.com/79896352/121104985-03682980-c7b8-11eb-8b0e-57e72b9fcf69.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can add their own cocktail to "My cocktailz"
- [x] Make all inputs required
- [x] Preview the image for the user to view
- [x] When cocktail is added, redirect to "My cocktailz" so user can view it
- [x] Make sure inputs value are cleared when redirecting to a different page
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
