### ISSUE TITLE
Feature 5: User can navigate

### ISSUE THREAD

**Issue by john-hc-hwang** [john-hc-hwang/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can navigate

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can navigate

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Left Tab](https://user-images.githubusercontent.com/79896352/121105490-116a7a00-c7b9-11eb-85eb-57f9ab2533b9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can navigate to "My cocktailz" by clicking tab and clicking on My cocktailz
- [x] User can navigate to "My cocktailz" by clickng on user Icon
- [x] User can return to main page with search and add features when "Cocktailz" main heading is clicked
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
